In [2]:
import pandas as pd

### Step 1: Open OnlineRetail.csv in Excel (*Complete project is done using Python only*) and use the Filter feature to display only the transactions made by customers from 'United Kingdom'. Count how many unique CustomerIDs made purchases from the UK.

In [3]:
retail_data = pd.read_csv('online_retail.csv')

In [18]:
retail_data.describe()

            Quantity      UnitPrice     CustomerID          Sales
count  541909.000000  541909.000000  406829.000000  541909.000000
mean        9.552250       4.611114   15287.690570      17.987795
std       218.081158      96.759853    1713.600303     378.810824
min    -80995.000000  -11062.060000   12346.000000 -168469.600000
25%         1.000000       1.250000   13953.000000       3.400000
50%         3.000000       2.080000   15152.000000       9.750000
75%        10.000000       4.130000   16791.000000      17.400000
max     80995.000000   38970.000000   18287.000000  168469.600000

In [5]:
uk = retail_data[retail_data['Country'] == 'United Kingdom']
print(uk.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

        InvoiceDate  UnitPrice  CustomerID         Country
0  01-12-2010 08:26       2.55     17850.0  United Kingdom
1  01-12-2010 08:26       3.39     17850.0  United Kingdom
2  01-12-2010 08:26       2.75     17850.0  United Kingdom
3  01-12-2010 08:26       3.39     17850.0  United Kingdom
4  01-12-2010 08:26       3.39     17850.0  United Kingdom

In [6]:
unique_count = uk['CustomerID'].nunique()
print("Count of unique CustomerIDs made purchases from the UK: ",unique_count)

Count of unique CustomerIDs made purchases from the UK:  3950

### Step 2: Create a PivotTable to *analyze total sales* (Quantity * UnitPrice) by Country. **Identify the top 3 countries by total sales** and write their names in a cell below your table.

In [7]:
retail_data['Sales'] = retail_data['Quantity'] * retail_data['UnitPrice']
retail_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34

In [8]:
pivot_table = retail_data.groupby('Country',as_index=False).agg(Total_Sales = ('Sales','sum')).sort_values('Total_Sales', ascending=False)

In [9]:
pivot_table.head(3)

''' Top 3 Countries by total sales are: UNITED KINGDOM, NETHERLANDS and EIRE'''

' Top 3 Countries by total sales are: UNITED KINGDOM, NETHERLANDS and EIRE'

### Step 3: Calculate the average order value (*total sales per InvoiceNo*) for all customers. Highlight any InvoiceNo where the order value is above ₹10,000.

In [10]:
''' Checking the relationship between InvoiceNo and CustomerID 
Question says to calculate avg order value = total sales per InvoiceNo. So i need to check whether 1 InvoiceNo = 1 Customer'''

check = retail_data.groupby('InvoiceNo')['CustomerID'].nunique()

# If this is 1, each invoice belongs to a single customer
if check.max() == 1:
        print('Each invoice belongs to a single customer')

Each invoice belongs to a single customer

In [11]:
''' Calculate total sales per InvoiceNo '''

invoice_sales = retail_data.groupby('InvoiceNo',as_index=False).agg(Order_Value = ('Sales','sum'))

In [12]:
''' Highlight invoices above ₹10,000 '''

high_value_invoices = invoice_sales[invoice_sales['Order_Value'] > 10000]

In [13]:
''' Calculate average order value across all invoices or for all customers '''

avg_order_value = invoice_sales['Order_Value'].mean()

print("Average Order Value:", round(avg_order_value,2))
print("\nInvoices above 10,000:\n", high_value_invoices)

Average Order Value: 376.36

Invoices above 10,000:
       InvoiceNo  Order_Value
329      536982     10661.69
652      537632     13541.33
660      537640     11540.34
674      537659     15885.49
1024     538351     12633.67
1230     538877     12681.58
1645     539750     18745.86
2018     540689     12797.52
2057     540815     15160.90
2202     541206     10389.06
2212     541220     16774.72
2303     541431     77183.60
3473     543989     14022.92
3744     544479     11956.10
4209     545475     16726.84
4849     546789     10065.00
5324     547708     11343.20
5513     548011     15719.56
5570     548203     21627.72
6741     550461     21535.90
7981     552883     14415.74
8313     553546     11924.80
9458     555920     10999.52
9654     556255     16488.00
9741     556444     38970.00
9951     556917     22775.93
10598    558262     10174.94
10728    558526     13355.40
11696    560445     11134.34
12289    561633     10303.95
12443    561901     13464.26
12686    562439     18841.48
12856    562789     12341.21
12935    562955     16677.26
12983    563076     19150.66
13237    563590     13031.50
13240    563614     21880.44
14828    566934     13249.94
14970    567280     10267.88
15038    567381     22104.80
15046    567423     31698.16
16118    569570     13760.02
16148    569650     15643.77
16238    569815     10992.96
17300    572035     20277.92
17393    572209     22206.00
18141    573585     16874.58
18776    574941     52940.94
19468    576365     50653.91
20497    578305     10584.77
21855    581175     10901.54
22007    581457     10363.82
22025    581483    168469.60
22061   A563185     11062.06

### Step 4: Perform a t-test to compare the *average order value between customers from 'France' and 'Germany'*. State whether the difference is statistically significant at the 0.05 level

In [14]:
invoice_sales_country_wise = retail_data.groupby(['InvoiceNo','Country'],as_index=False).agg(Order_Value = ('Sales','sum'))

In [15]:
france_orders = invoice_sales_country_wise[invoice_sales_country_wise['Country'] == 'France']['Order_Value']
germany_orders = invoice_sales_country_wise[invoice_sales_country_wise['Country'] == 'Germany']['Order_Value']

In [16]:
''' France vs Germany side by side with their averages and invoice counts '''

avg_df = pd.DataFrame({
    'Country': ['France', 'Germany'],
    'Average_Order_Value': [france_orders.mean(), germany_orders.mean()],
    'Invoice_Count': [france_orders.count(), germany_orders.count()]
})

print(avg_df)

   Country  Average_Order_Value  Invoice_Count
0   France           428.208026            461
1  Germany           367.658723            603

In [17]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(france_orders, germany_orders, equal_var=False)
alpha = 0.05   # Given in the problem statement
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print('The difference in average order value between France and Germany is statistically significant')
else:
    print('The difference is not significant at the 0.05 level')

t-statistic: 1.3914908934559311
p-value: 0.1644543898938908
The difference is not significant at the 0.05 level